'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class BajasMateriales
        Inherits XPLiteObject
        Dim fIdBaja As Integer
        <Key(True)>
        Public Property IdBaja() As Integer
            Get
                Return fIdBaja
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdBaja", fIdBaja, value)
            End Set
        End Property
        Dim fCantidad As Decimal
        Public Property Cantidad() As Decimal
            Get
                Return fCantidad
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Cantidad", fCantidad, value)
            End Set
        End Property
        Dim fFechaBaja As DateTime
        Public Property FechaBaja() As DateTime
            Get
                Return fFechaBaja
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FechaBaja", fFechaBaja, value)
            End Set
        End Property
        Dim fMotivoBaja As Integer
        Public Property MotivoBaja() As Integer
            Get
                Return fMotivoBaja
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("MotivoBaja", fMotivoBaja, value)
            End Set
        End Property
        Dim fObservaciones As String
        <Size(SizeAttribute.Unlimited)>
        Public Property Observaciones() As String
            Get
                Return fObservaciones
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Observaciones", fObservaciones, value)
            End Set
        End Property
        Dim fIdProducto As Integer
        Public Property IdProducto() As Integer
            Get
                Return fIdProducto
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdProducto", fIdProducto, value)
            End Set
        End Property
        Dim fSector As String
        <Size(50)>
        Public Property Sector() As String
            Get
                Return fSector
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Sector", fSector, value)
            End Set
        End Property
    End Class

End Namespace
