'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class EstadosPedido
        Inherits XPLiteObject
        Dim fIdEstado As Integer
        <Key(True)>
        Public Property IdEstado() As Integer
            Get
                Return fIdEstado
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdEstado", fIdEstado, value)
            End Set
        End Property
        Dim fEstado As String
        <Size(50)>
        Public Property Estado() As String
            Get
                Return fEstado
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Estado", fEstado, value)
            End Set
        End Property
    End Class

End Namespace
