'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class Monedas
        Inherits XPLiteObject
        Dim fIdMoneda As Integer
        <Key(True)>
        Public Property IdMoneda() As Integer
            Get
                Return fIdMoneda
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdMoneda", fIdMoneda, value)
            End Set
        End Property
        Dim fMoneda As String
        <Size(50)>
        Public Property Moneda() As String
            Get
                Return fMoneda
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Moneda", fMoneda, value)
            End Set
        End Property
    End Class

End Namespace
