'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class MotivosBaja
        Inherits XPLiteObject
        Dim fIdMotivoBaja As Integer
        <Key(True)>
        Public Property IdMotivoBaja() As Integer
            Get
                Return fIdMotivoBaja
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdMotivoBaja", fIdMotivoBaja, value)
            End Set
        End Property
        Dim fMotivoBaja As String
        <Size(250)>
        Public Property MotivoBaja() As String
            Get
                Return fMotivoBaja
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("MotivoBaja", fMotivoBaja, value)
            End Set
        End Property
    End Class

End Namespace
