'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class OrdenCompraDetalles
        Inherits XPLiteObject
        Dim fIdDetOC As Integer
        <Key(True)>
        Public Property IdDetOC() As Integer
            Get
                Return fIdDetOC
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdDetOC", fIdDetOC, value)
            End Set
        End Property
        Dim fIdOC As OrdenesCompra
        <Association("OrdenCompraDetallesReferencesOrdenesCompra")>
        Public Property IdOC() As OrdenesCompra
            Get
                Return fIdOC
            End Get
            Set(ByVal value As OrdenesCompra)
                SetPropertyValue(Of OrdenesCompra)("IdOC", fIdOC, value)
            End Set
        End Property
        Dim fIdProducto As Integer
        Public Property IdProducto() As Integer
            Get
                Return fIdProducto
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdProducto", fIdProducto, value)
            End Set
        End Property
        Dim fCantidad As Decimal
        Public Property Cantidad() As Decimal
            Get
                Return fCantidad
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Cantidad", fCantidad, value)
            End Set
        End Property
        Dim fIdPedido As Integer
        Public Property IdPedido() As Integer
            Get
                Return fIdPedido
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdPedido", fIdPedido, value)
            End Set
        End Property
    End Class

End Namespace
