'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class OrdenesCompra
        Inherits XPLiteObject
        Dim fIdOrdenCompra As Integer
        <Key(True)>
        Public Property IdOrdenCompra() As Integer
            Get
                Return fIdOrdenCompra
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdOrdenCompra", fIdOrdenCompra, value)
            End Set
        End Property
        Dim fIdproveedor As Integer
        Public Property Idproveedor() As Integer
            Get
                Return fIdproveedor
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Idproveedor", fIdproveedor, value)
            End Set
        End Property
        Dim fFechaCompra As DateTime
        Public Property FechaCompra() As DateTime
            Get
                Return fFechaCompra
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FechaCompra", fFechaCompra, value)
            End Set
        End Property
        Dim fMoneda As Integer
        Public Property Moneda() As Integer
            Get
                Return fMoneda
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Moneda", fMoneda, value)
            End Set
        End Property
        Dim fFinalizada As Integer
        Public Property Finalizada() As Integer
            Get
                Return fFinalizada
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Finalizada", fFinalizada, value)
            End Set
        End Property
        <Association("OrdenCompraDetallesReferencesOrdenesCompra")>
        Public ReadOnly Property OrdenCompraDetallesCollection() As XPCollection(Of OrdenCompraDetalles)
            Get
                Return GetCollection(Of OrdenCompraDetalles)("OrdenCompraDetallesCollection")
            End Get
        End Property
    End Class

End Namespace
