'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class Paises
        Inherits XPLiteObject
        Dim fPais As String
        <Size(80)>
        Public Property Pais() As String
            Get
                Return fPais
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Pais", fPais, value)
            End Set
        End Property
        Dim fIdpais As Integer
        <Key(True)>
        Public Property Idpais() As Integer
            Get
                Return fIdpais
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Idpais", fIdpais, value)
            End Set
        End Property
    End Class

End Namespace
