'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class PedidosPedidosCollection_PedidosDetallesPedidosDetallesCollection
        Inherits XPObject
        Dim fPedidosDetallesCollection As PedidosDetalles
        <Association("PedidosPedidosCollection_PedidosDetallesPedidosDetallesCollectionReferencesPedidosDetalles")>
        Public Property PedidosDetallesCollection() As PedidosDetalles
            Get
                Return fPedidosDetallesCollection
            End Get
            Set(ByVal value As PedidosDetalles)
                SetPropertyValue(Of PedidosDetalles)("PedidosDetallesCollection", fPedidosDetallesCollection, value)
            End Set
        End Property
        Dim fPedidosCollection As Pedidos
        <Association("PedidosPedidosCollection_PedidosDetallesPedidosDetallesCollectionReferencesPedidos")>
        Public Property PedidosCollection() As Pedidos
            Get
                Return fPedidosCollection
            End Get
            Set(ByVal value As Pedidos)
                SetPropertyValue(Of Pedidos)("PedidosCollection", fPedidosCollection, value)
            End Set
        End Property
    End Class

End Namespace
