'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class PedidosDetalles
        Inherits XPLiteObject
        Dim fIdDetalle As Integer
        <Key(True)>
        Public Property IdDetalle() As Integer
            Get
                Return fIdDetalle
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdDetalle", fIdDetalle, value)
            End Set
        End Property
        Dim fIdPedido As Integer
        Public Property IdPedido() As Integer
            Get
                Return fIdPedido
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdPedido", fIdPedido, value)
            End Set
        End Property
        Dim fIdProducto As Integer
        Public Property IdProducto() As Integer
            Get
                Return fIdProducto
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdProducto", fIdProducto, value)
            End Set
        End Property
        Dim fCantidad As Decimal
        Public Property Cantidad() As Decimal
            Get
                Return fCantidad
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Cantidad", fCantidad, value)
            End Set
        End Property
        Dim fObservaciones As String
        <Size(SizeAttribute.Unlimited)>
        Public Property Observaciones() As String
            Get
                Return fObservaciones
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Observaciones", fObservaciones, value)
            End Set
        End Property
        Dim fPrecioProducto As Decimal
        Public Property PrecioProducto() As Decimal
            Get
                Return fPrecioProducto
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("PrecioProducto", fPrecioProducto, value)
            End Set
        End Property
        Dim fIdProveedor As Integer
        Public Property IdProveedor() As Integer
            Get
                Return fIdProveedor
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdProveedor", fIdProveedor, value)
            End Set
        End Property
        Dim fODCEnviada As Integer
        Public Property ODCEnviada() As Integer
            Get
                Return fODCEnviada
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("ODCEnviada", fODCEnviada, value)
            End Set
        End Property
    End Class

End Namespace
