'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class Pedidos
        Inherits XPLiteObject
        Dim fSector As Integer
        Public Property Sector() As Integer
            Get
                Return fSector
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Sector", fSector, value)
            End Set
        End Property
        Dim fFechaPedido As DateTime
        Public Property FechaPedido() As DateTime
            Get
                Return fFechaPedido
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FechaPedido", fFechaPedido, value)
            End Set
        End Property
        Dim fResponsable As String
        <Size(200)>
        Public Property Responsable() As String
            Get
                Return fResponsable
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Responsable", fResponsable, value)
            End Set
        End Property
        Dim fIdPedido As Integer
        <Key(True)>
        Public Property IdPedido() As Integer
            Get
                Return fIdPedido
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdPedido", fIdPedido, value)
            End Set
        End Property
        Dim fEstado As Integer
        Public Property Estado() As Integer
            Get
                Return fEstado
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Estado", fEstado, value)
            End Set
        End Property
        Dim fObservaciones As String
        <Size(SizeAttribute.Unlimited)>
        Public Property Observaciones() As String
            Get
                Return fObservaciones
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Observaciones", fObservaciones, value)
            End Set
        End Property
        Dim fFechaRecepcion As DateTime
        Public Property FechaRecepcion() As DateTime
            Get
                Return fFechaRecepcion
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FechaRecepcion", fFechaRecepcion, value)
            End Set
        End Property
        Dim fUrgente As String
        <Size(20)>
        Public Property Urgente() As String
            Get
                Return fUrgente
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Urgente", fUrgente, value)
            End Set
        End Property
        Dim fAutorizadoPor As String
        <Size(255)>
        Public Property AutorizadoPor() As String
            Get
                Return fAutorizadoPor
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("AutorizadoPor", fAutorizadoPor, value)
            End Set
        End Property
        Dim fFechaAprobacion As DateTime
        Public Property FechaAprobacion() As DateTime
            Get
                Return fFechaAprobacion
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FechaAprobacion", fFechaAprobacion, value)
            End Set
        End Property
    End Class

End Namespace
