'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class Productos
        Inherits XPLiteObject
        Dim fId As Integer
        <Key(True)>
        Public Property Id() As Integer
            Get
                Return fId
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Id", fId, value)
            End Set
        End Property
        Dim fRubro As String
        <Size(50)>
        Public Property Rubro() As String
            Get
                Return fRubro
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Rubro", fRubro, value)
            End Set
        End Property
        Dim fSubrubro As String
        <Size(50)>
        Public Property Subrubro() As String
            Get
                Return fSubrubro
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Subrubro", fSubrubro, value)
            End Set
        End Property
        Dim fCodigoProducto As String
        <Size(50)>
        Public Property CodigoProducto() As String
            Get
                Return fCodigoProducto
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CodigoProducto", fCodigoProducto, value)
            End Set
        End Property
        Dim fProducto As String
        Public Property Producto() As String
            Get
                Return fProducto
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Producto", fProducto, value)
            End Set
        End Property
        Dim fMarca As String
        <Size(80)>
        Public Property Marca() As String
            Get
                Return fMarca
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Marca", fMarca, value)
            End Set
        End Property
        Dim fPresentacion As String
        <Size(80)>
        Public Property Presentacion() As String
            Get
                Return fPresentacion
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Presentacion", fPresentacion, value)
            End Set
        End Property
    End Class

End Namespace
