'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class RecepcionProductos
        Inherits XPLiteObject
        Dim fIdRecepcion As Integer
        <Key(True)>
        Public Property IdRecepcion() As Integer
            Get
                Return fIdRecepcion
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdRecepcion", fIdRecepcion, value)
            End Set
        End Property
        Dim fIdProducto As Integer
        Public Property IdProducto() As Integer
            Get
                Return fIdProducto
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdProducto", fIdProducto, value)
            End Set
        End Property
        Dim fCantidad As Decimal
        Public Property Cantidad() As Decimal
            Get
                Return fCantidad
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Cantidad", fCantidad, value)
            End Set
        End Property
        Dim fIdremito As Integer
        Public Property Idremito() As Integer
            Get
                Return fIdremito
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Idremito", fIdremito, value)
            End Set
        End Property
    End Class

End Namespace
