'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class Roles
        Inherits XPLiteObject
        Dim fId As Integer
        <Key(True)>
        Public Property Id() As Integer
            Get
                Return fId
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Id", fId, value)
            End Set
        End Property
        Dim fRol As String
        <Size(30)>
        Public Property Rol() As String
            Get
                Return fRol
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Rol", fRol, value)
            End Set
        End Property
        Dim fDescripcion As String
        <Size(150)>
        Public Property Descripcion() As String
            Get
                Return fDescripcion
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Descripcion", fDescripcion, value)
            End Set
        End Property
    End Class

End Namespace
