'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class Rubros
        Inherits XPLiteObject
        Dim fIdRubro As Integer
        <Key(True)>
        Public Property IdRubro() As Integer
            Get
                Return fIdRubro
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdRubro", fIdRubro, value)
            End Set
        End Property
        Dim fRubro As String
        <Size(80)>
        Public Property Rubro() As String
            Get
                Return fRubro
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Rubro", fRubro, value)
            End Set
        End Property
        Dim fSubrubro As String
        <Size(80)>
        Public Property Subrubro() As String
            Get
                Return fSubrubro
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Subrubro", fSubrubro, value)
            End Set
        End Property
    End Class

End Namespace
