'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class Stock
        Inherits XPLiteObject
        Dim fId As Integer
        <Key(True)>
        Public Property Id() As Integer
            Get
                Return fId
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Id", fId, value)
            End Set
        End Property
        Dim fStockMinimo As Decimal
        Public Property StockMinimo() As Decimal
            Get
                Return fStockMinimo
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("StockMinimo", fStockMinimo, value)
            End Set
        End Property
        Dim fStock1 As Decimal
        <Persistent("Stock")>
        Public Property Stock1() As Decimal
            Get
                Return fStock1
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Stock1", fStock1, value)
            End Set
        End Property
        Dim fFechaModificacion As DateTime
        Public Property FechaModificacion() As DateTime
            Get
                Return fFechaModificacion
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FechaModificacion", fFechaModificacion, value)
            End Set
        End Property
        Dim fIdProducto As Integer
        Public Property IdProducto() As Integer
            Get
                Return fIdProducto
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdProducto", fIdProducto, value)
            End Set
        End Property
        Dim fDelSector As Integer
        Public Property DelSector() As Integer
            Get
                Return fDelSector
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("DelSector", fDelSector, value)
            End Set
        End Property
    End Class

End Namespace
