'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    <NonPersistent()>
    Partial Public Class Usuariostags
        Inherits XPLiteObject
        Dim fRow As Long
        Public Property Row() As Long
            Get
                Return fRow
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Row", fRow, value)
            End Set
        End Property
        Dim fUsuarioID As String
        <Size(30)>
        Public Property UsuarioID() As String
            Get
                Return fUsuarioID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("UsuarioID", fUsuarioID, value)
            End Set
        End Property
        Dim fContraseña As String
        <Size(60)>
        Public Property Contraseña() As String
            Get
                Return fContraseña
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Contraseña", fContraseña, value)
            End Set
        End Property
        Dim fPermiso As String
        <Size(1)>
        Public Property Permiso() As String
            Get
                Return fPermiso
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Permiso", fPermiso, value)
            End Set
        End Property
        Dim fTag As String
        <Size(5)>
        Public Property Tag() As String
            Get
                Return fTag
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Tag", fTag, value)
            End Set
        End Property
        Dim fIdRol As Integer
        Public Property IdRol() As Integer
            Get
                Return fIdRol
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdRol", fIdRol, value)
            End Set
        End Property
        Dim fId As Integer
        Public Property Id() As Integer
            Get
                Return fId
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Id", fId, value)
            End Set
        End Property
    End Class

End Namespace
