'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    <NonPersistent()>
    Partial Public Class VerUsuariorolobjetopermiso
        Inherits XPLiteObject
        Dim fRow As Long
        Public Property Row() As Long
            Get
                Return fRow
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Row", fRow, value)
            End Set
        End Property
        Dim fUsuarioID As String
        <Size(30)>
        Public Property UsuarioID() As String
            Get
                Return fUsuarioID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("UsuarioID", fUsuarioID, value)
            End Set
        End Property
        Dim fContraseña As String
        <Size(60)>
        Public Property Contraseña() As String
            Get
                Return fContraseña
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Contraseña", fContraseña, value)
            End Set
        End Property
        Dim fApellidos As String
        <Size(30)>
        Public Property Apellidos() As String
            Get
                Return fApellidos
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Apellidos", fApellidos, value)
            End Set
        End Property
        Dim fNombres As String
        <Size(30)>
        Public Property Nombres() As String
            Get
                Return fNombres
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Nombres", fNombres, value)
            End Set
        End Property
        Dim fIdRol As Integer
        Public Property IdRol() As Integer
            Get
                Return fIdRol
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdRol", fIdRol, value)
            End Set
        End Property
        Dim fRol As String
        <Size(30)>
        Public Property Rol() As String
            Get
                Return fRol
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Rol", fRol, value)
            End Set
        End Property
        Dim fDescripcionRol As String
        <Size(150)>
        Public Property DescripcionRol() As String
            Get
                Return fDescripcionRol
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("DescripcionRol", fDescripcionRol, value)
            End Set
        End Property
        Dim fObjeto As String
        <Size(30)>
        Public Property Objeto() As String
            Get
                Return fObjeto
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Objeto", fObjeto, value)
            End Set
        End Property
        Dim fDescripcionObjeto As String
        <Size(150)>
        Public Property DescripcionObjeto() As String
            Get
                Return fDescripcionObjeto
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("DescripcionObjeto", fDescripcionObjeto, value)
            End Set
        End Property
        Dim fPermiso As String
        <Size(1)>
        Public Property Permiso() As String
            Get
                Return fPermiso
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Permiso", fPermiso, value)
            End Set
        End Property
    End Class

End Namespace
