'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    <NonPersistent()>
    Partial Public Class VistaBusquedaPedidos
        Inherits XPLiteObject
        Dim fIdPedido As Integer
        Public Property IdPedido() As Integer
            Get
                Return fIdPedido
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdPedido", fIdPedido, value)
            End Set
        End Property
        Dim fIdProducto As Integer
        Public Property IdProducto() As Integer
            Get
                Return fIdProducto
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdProducto", fIdProducto, value)
            End Set
        End Property
        Dim fCantidad As Decimal
        Public Property Cantidad() As Decimal
            Get
                Return fCantidad
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Cantidad", fCantidad, value)
            End Set
        End Property
        Dim fObservaciones As String
        <Size(SizeAttribute.Unlimited)>
        Public Property Observaciones() As String
            Get
                Return fObservaciones
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Observaciones", fObservaciones, value)
            End Set
        End Property
        Dim fSector As Integer
        Public Property Sector() As Integer
            Get
                Return fSector
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Sector", fSector, value)
            End Set
        End Property
        Dim fFechaPedido As DateTime
        Public Property FechaPedido() As DateTime
            Get
                Return fFechaPedido
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FechaPedido", fFechaPedido, value)
            End Set
        End Property
        Dim fResponsable As String
        <Size(200)>
        Public Property Responsable() As String
            Get
                Return fResponsable
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Responsable", fResponsable, value)
            End Set
        End Property
        Dim fEstado As Integer
        Public Property Estado() As Integer
            Get
                Return fEstado
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Estado", fEstado, value)
            End Set
        End Property
        Dim fFechaRecepcion As DateTime
        Public Property FechaRecepcion() As DateTime
            Get
                Return fFechaRecepcion
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FechaRecepcion", fFechaRecepcion, value)
            End Set
        End Property
        Dim fIdDetalle As Integer
        Public Property IdDetalle() As Integer
            Get
                Return fIdDetalle
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdDetalle", fIdDetalle, value)
            End Set
        End Property
        Dim fPrecioProducto As Decimal
        Public Property PrecioProducto() As Decimal
            Get
                Return fPrecioProducto
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("PrecioProducto", fPrecioProducto, value)
            End Set
        End Property
        Dim fId As Integer
        Public Property Id() As Integer
            Get
                Return fId
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Id", fId, value)
            End Set
        End Property
        Dim fRubro As String
        <Size(50)>
        Public Property Rubro() As String
            Get
                Return fRubro
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Rubro", fRubro, value)
            End Set
        End Property
        Dim fSubrubro As String
        <Size(50)>
        Public Property Subrubro() As String
            Get
                Return fSubrubro
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Subrubro", fSubrubro, value)
            End Set
        End Property
        Dim fCodigoProducto As String
        <Size(50)>
        Public Property CodigoProducto() As String
            Get
                Return fCodigoProducto
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CodigoProducto", fCodigoProducto, value)
            End Set
        End Property
        Dim fProducto As String
        Public Property Producto() As String
            Get
                Return fProducto
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Producto", fProducto, value)
            End Set
        End Property
        Dim fMarca As String
        <Size(80)>
        Public Property Marca() As String
            Get
                Return fMarca
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Marca", fMarca, value)
            End Set
        End Property
        Dim fPresentacion As String
        <Size(80)>
        Public Property Presentacion() As String
            Get
                Return fPresentacion
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Presentacion", fPresentacion, value)
            End Set
        End Property
        Dim fIdProveedor As Integer
        Public Property IdProveedor() As Integer
            Get
                Return fIdProveedor
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdProveedor", fIdProveedor, value)
            End Set
        End Property
    End Class

End Namespace
