'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class VistaODC
        Inherits XPLiteObject
        Dim fRow As Long
        <Key()>
        Public Property Row() As Long
            Get
                Return fRow
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Row", fRow, value)
            End Set
        End Property
        Dim fIdPedido As Integer
        Public Property IdPedido() As Integer
            Get
                Return fIdPedido
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdPedido", fIdPedido, value)
            End Set
        End Property
        Dim fObservaciones As String
        <Size(SizeAttribute.Unlimited)>
        Public Property Observaciones() As String
            Get
                Return fObservaciones
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Observaciones", fObservaciones, value)
            End Set
        End Property
        Dim fIdProducto As Integer
        Public Property IdProducto() As Integer
            Get
                Return fIdProducto
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdProducto", fIdProducto, value)
            End Set
        End Property
        Dim fIdProveedor As Integer
        Public Property IdProveedor() As Integer
            Get
                Return fIdProveedor
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdProveedor", fIdProveedor, value)
            End Set
        End Property
        Dim fRazonSocial As String
        <Size(80)>
        Public Property RazonSocial() As String
            Get
                Return fRazonSocial
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RazonSocial", fRazonSocial, value)
            End Set
        End Property
        Dim fDomicilio As String
        <Size(150)>
        Public Property Domicilio() As String
            Get
                Return fDomicilio
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Domicilio", fDomicilio, value)
            End Set
        End Property
        Dim fLocalidad As String
        <Size(80)>
        Public Property Localidad() As String
            Get
                Return fLocalidad
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Localidad", fLocalidad, value)
            End Set
        End Property
        Dim fEmail As String
        <Size(50)>
        Public Property Email() As String
            Get
                Return fEmail
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Email", fEmail, value)
            End Set
        End Property
        Dim fProducto As String
        Public Property Producto() As String
            Get
                Return fProducto
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Producto", fProducto, value)
            End Set
        End Property
        Dim fobs1 As String
        <Size(SizeAttribute.Unlimited)>
        Public Property obs1() As String
            Get
                Return fobs1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("obs1", fobs1, value)
            End Set
        End Property
        Dim fCUIT_CUIL As String
        <Size(15)>
        Public Property CUIT_CUIL() As String
            Get
                Return fCUIT_CUIL
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CUIT_CUIL", fCUIT_CUIL, value)
            End Set
        End Property
        Dim fUrgente As String
        <Size(20)>
        Public Property Urgente() As String
            Get
                Return fUrgente
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Urgente", fUrgente, value)
            End Set
        End Property
        Dim fCantidad As Decimal
        Public Property Cantidad() As Decimal
            Get
                Return fCantidad
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Cantidad", fCantidad, value)
            End Set
        End Property
        Dim fPrecioProducto As Decimal
        Public Property PrecioProducto() As Decimal
            Get
                Return fPrecioProducto
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("PrecioProducto", fPrecioProducto, value)
            End Set
        End Property
        Dim fTotalProducto As Decimal
        Public Property TotalProducto() As Decimal
            Get
                Return fTotalProducto
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotalProducto", fTotalProducto, value)
            End Set
        End Property
        Dim fEstado As Integer
        Public Property Estado() As Integer
            Get
                Return fEstado
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Estado", fEstado, value)
            End Set
        End Property
        Dim fODCEnviada As Integer
        Public Property ODCEnviada() As Integer
            Get
                Return fODCEnviada
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("ODCEnviada", fODCEnviada, value)
            End Set
        End Property
    End Class

End Namespace
