'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class VistaPedidosDetalle
        Inherits XPLiteObject
        Dim fRow As Long
        <Key()>
        Public Property Row() As Long
            Get
                Return fRow
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Row", fRow, value)
            End Set
        End Property
        Dim fFechaPedido As DateTime
        Public Property FechaPedido() As DateTime
            Get
                Return fFechaPedido
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FechaPedido", fFechaPedido, value)
            End Set
        End Property
        Dim fResponsable As String
        <Size(200)>
        Public Property Responsable() As String
            Get
                Return fResponsable
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Responsable", fResponsable, value)
            End Set
        End Property
        Dim fObservaciones As String
        <Size(SizeAttribute.Unlimited)>
        Public Property Observaciones() As String
            Get
                Return fObservaciones
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Observaciones", fObservaciones, value)
            End Set
        End Property
        Dim fFechaRecepcion As DateTime
        Public Property FechaRecepcion() As DateTime
            Get
                Return fFechaRecepcion
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FechaRecepcion", fFechaRecepcion, value)
            End Set
        End Property
        Dim fCantidad As Decimal
        Public Property Cantidad() As Decimal
            Get
                Return fCantidad
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Cantidad", fCantidad, value)
            End Set
        End Property
        Dim fObsb1 As String
        <Size(SizeAttribute.Unlimited)>
        Public Property Obsb1() As String
            Get
                Return fObsb1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Obsb1", fObsb1, value)
            End Set
        End Property
        Dim fPrecioProducto As Decimal
        Public Property PrecioProducto() As Decimal
            Get
                Return fPrecioProducto
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("PrecioProducto", fPrecioProducto, value)
            End Set
        End Property
        Dim fRazonSocial As String
        <Size(80)>
        Public Property RazonSocial() As String
            Get
                Return fRazonSocial
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RazonSocial", fRazonSocial, value)
            End Set
        End Property
        Dim fNombreFantasia As String
        <Size(80)>
        Public Property NombreFantasia() As String
            Get
                Return fNombreFantasia
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NombreFantasia", fNombreFantasia, value)
            End Set
        End Property
        Dim fProducto As String
        Public Property Producto() As String
            Get
                Return fProducto
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Producto", fProducto, value)
            End Set
        End Property
        Dim fIdPedido As Integer
        Public Property IdPedido() As Integer
            Get
                Return fIdPedido
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdPedido", fIdPedido, value)
            End Set
        End Property
        Dim fSector As Integer
        Public Property Sector() As Integer
            Get
                Return fSector
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Sector", fSector, value)
            End Set
        End Property
        Dim fEstado As Integer
        Public Property Estado() As Integer
            Get
                Return fEstado
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Estado", fEstado, value)
            End Set
        End Property
    End Class

End Namespace
