'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    <NonPersistent()>
    Partial Public Class VistaDatosPedidos
        Inherits XPLiteObject
        Dim fIdPedido As Integer
        Public Property IdPedido() As Integer
            Get
                Return fIdPedido
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdPedido", fIdPedido, value)
            End Set
        End Property
        Dim fFechaPedido As DateTime
        Public Property FechaPedido() As DateTime
            Get
                Return fFechaPedido
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FechaPedido", fFechaPedido, value)
            End Set
        End Property
        Dim fResponsable As String
        <Size(200)>
        Public Property Responsable() As String
            Get
                Return fResponsable
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Responsable", fResponsable, value)
            End Set
        End Property
        Dim fEstado As String
        <Size(50)>
        Public Property Estado() As String
            Get
                Return fEstado
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Estado", fEstado, value)
            End Set
        End Property
        Dim fSector As String
        <Size(80)>
        Public Property Sector() As String
            Get
                Return fSector
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Sector", fSector, value)
            End Set
        End Property
        Dim fCantidad As Decimal
        Public Property Cantidad() As Decimal
            Get
                Return fCantidad
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Cantidad", fCantidad, value)
            End Set
        End Property
        Dim fPrecioProducto As Decimal
        Public Property PrecioProducto() As Decimal
            Get
                Return fPrecioProducto
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("PrecioProducto", fPrecioProducto, value)
            End Set
        End Property
        Dim fRazonSocial As String
        <Size(80)>
        Public Property RazonSocial() As String
            Get
                Return fRazonSocial
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RazonSocial", fRazonSocial, value)
            End Set
        End Property
        Dim fNombreFantasia As String
        <Size(80)>
        Public Property NombreFantasia() As String
            Get
                Return fNombreFantasia
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NombreFantasia", fNombreFantasia, value)
            End Set
        End Property
        Dim fRubro As String
        <Size(50)>
        Public Property Rubro() As String
            Get
                Return fRubro
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Rubro", fRubro, value)
            End Set
        End Property
        Dim fSubrubro As String
        <Size(50)>
        Public Property Subrubro() As String
            Get
                Return fSubrubro
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Subrubro", fSubrubro, value)
            End Set
        End Property
        Dim fProducto As String
        Public Property Producto() As String
            Get
                Return fProducto
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Producto", fProducto, value)
            End Set
        End Property
        Dim fMarca As String
        <Size(80)>
        Public Property Marca() As String
            Get
                Return fMarca
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Marca", fMarca, value)
            End Set
        End Property
        Dim fPresentacion As String
        <Size(80)>
        Public Property Presentacion() As String
            Get
                Return fPresentacion
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Presentacion", fPresentacion, value)
            End Set
        End Property
        Dim fIdOC As Integer
        Public Property IdOC() As Integer
            Get
                Return fIdOC
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdOC", fIdOC, value)
            End Set
        End Property
        Dim fFechaCompra As DateTime
        Public Property FechaCompra() As DateTime
            Get
                Return fFechaCompra
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FechaCompra", fFechaCompra, value)
            End Set
        End Property
    End Class

End Namespace
